---
title: "Marcos Abreu"
author: Marcos Abreu
output: pagedown::html_resume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aside
========================================================

Objetivo
--------------------------------------------------------

Gerente de Projetos


Contato
--------------------------------------------------------

<i class="fa fa-mobile"/>  +55 41 99955-8383     
<i class="far fa-envelope"/> [abreums@gmail.com](mailto:abreums@gmail.com)     
<i class="fa fa-linkedin"/> [marcos-abreu-82216b](http://linkedin.com/in/marcos-abreu-82216b)     
<i class="fa fa-github"/>  [abreums.github.io](https://abreums.github.io)    

Idiomas
--------------------------------------------------------

<i class="fa fa-globe-americas"/>  Inglês - Fluente    
<i class="fa fa-globe-americas"/>  Espanhol - Intermediário    
<i class="fa fa-globe-americas"/>  Português - Nativo    


Disclaimer
--------------------------------------------------------

[Github blog](https://abreums.github.io) 


Main
========================================================

Marcos Abreu {#title}
--------------------------------------------------------

Tive a oportunidade de atuar em empresas e governos de diferentes áreas de negócio, e países, o que me ajudou a formar uma visão diversificada de negócio e soluções. Tenho experiência com gerenciamento de projetos, programas, portfólios, planejamento estratégico, gestão de mundanças, desenvolvimento e implantação de sistemas. 


Formação {data-icon=graduation-cap}
-------------------------------------------------------

### MBA em Gerenciamento de Projetos    

ISAE-FGV

Curitiba - PR    

2003 - 2002    

### Engenharia Elétrica

Universidade Estadual de Campinas

Campinas - SP    

1991 - 1987   

### Certificação PMP

_Project Management Professional_

PMI    

Ativa - 2003   



Experiência {data-icon=briefcase}
--------------------------------------------------------


### Exxon Mobil

Change Management Advisor

Curitiba - PR

até data - 2021/08
    
    
Realizações:    
    
-  *Gerenciamento de Mudanças* na área de Químicos, Lubrificantes e Combustíveis para projetos de _Data Analytics_ e _Machine Learning_ envolvendo
**Supply Chain** e **Manufacturing Processes**.   


### G4F Soluções Corporativas

Gerente de Projetos

Curitiba - PR

2021/07 - 2020/11
    
    
Realizações:    
    
- COPEL-Distribuição: Gerente de Projetos e Gerente de Mudanças responsável para os Programas [Paraná Trifásico](https://www.youtube.com/watch?v=_BCvrXCLxl8&t=4s) e Confiabilidade Total.    

### FH (atualmente NTT Data)

Gerente de Projetos

Curitiba - PR

2020/02 - 2016/04
    
    
Realizações:    
    
- Pifpaf Ailmentos: desenvolvimento e implantação de B2B, B2C, Sales/CRM, Marketing e mobile-PWA.    
- Pearson Education: implantação de B2B integrado com Salesforce.     
- DPaschoal: desenvolvimento e implantação de B2C e Venda Assistida (_Omni-Channel_).     
- Leroy Merlin: desenvolvimento de Venda Assistida.   

### Instituto de Compras Governamentais - ICG

Gerente de Projetos

São Paulo - SP

2016/01 - 2013/09
    
    
Realizações:    
    
- SEBRAE-Nacional: desenvolvimento e implantação de *sistema de BI* para monitoramento de indicadores de compras governamentais.  
- Governo de Moçambique: *Gerenciamento de Mudanças Corporativas* - desenvolvimento e realização de plano de gestão de mudanças para a implantação de novos processos e sistemas de compras governamentais. *Gerenciamento de Projetos* - desenvolvimento e implantação de sistemas de Catálogos de Produtos e Serviços, Cadastro de Fornecedores e Processos de Compras.    

::: aside    
Atuar no desenvolvimento de sistemas com equipes distribuídas em dois continentes, e conduzir o Plano de Gestão de Mudanças com impacto abrangente na administração federal foi um dos trabalhos mais desafiadores que já realizei.    
:::     


### Konsultex

Gerente de Projetos

São Paulo - SP

2013/08 - 2012/06
    
    
Realizações:    
    
- PROCERGS: implantação de sistemas de automação de processos e gestão arquivística.

::: aside    
Possuo experiência com gerencimento de projetos de desenvolvimento e integração de sistemas, automação de processos, gestão arquivística, inovação tecnológica, sistemas comerciais, financeiros e industriais, e mais recentemente com projetos de Governança de Dados, sistemas de _Data Analytics_ e _Machine Learning_.    
:::     

### PM21

Gerente de Projetos

Curitiba - PR

2011/11 - 2003/06    
    
    
Realizações:    
    
- Parque Tecnológico Itaipu: gerenciamento do projeto Baterias de Sódio de transferência internacional de tecnologia.    
- Mapfre Seguros Brasil e Mapfre Seguros Argentina: implantação de Escritório de Projetos.   
- TRT4: Implantação de _Práticas Ágeis_ na Secretaria de Tecnologia da Informação.   
- Ministério do Meio Ambiente (MMA): Reestruturação do Programa Pantanal e _Planejamento Estratégico_ da Secretaria de Desenvolvimento Rural Sustentável.    
- Secretaria de Planejamento do Mato Grosso: Implantação de Escritório de Projetos.    
- Consórcio CONPAR: gerenciamento de *riscos* para as obras de expansão da Refinaria Presidente Vargas.
- Colseguros - _Colômbia_: implantação de solução A7 de Gestão de Portfólios e Riscos de Portfólios.


Trabalho Voluntário {data-icon=chalkboard-teacher}
--------------------------------------------------------

### Research - The Value of Project Management

Athabasca University

Calgary - CA

2008 - 2007
    
Representante do Brasil no projeto de pesquisa conduzido pela Universidade de Athabasca e patrocinado pelo PMI.

### Brigada Code-For-São Paulo

[Code-For-All](https://codeforall.org/)

São Paulo - SP

2016 - 2018
    
Coordenador da brigada Code-For-São Paulo de trabalho voluntário com desenvolvimento de sistemas, integrando do Code-For-All.


::: aside    
Desenvolvi meus conhecimentos com <strong>Gestão de Mudanças</strong> utilizando como base os trabalhos de [John Kotter](https://en.wikipedia.org/wiki/John_Kotter) e [Kurt Lewin](https://en.wikipedia.org/wiki/Kurt_Lewin), dentre outros. Na COPEL, estive utilizando o método *People Centred Implementation* (PCI) desenvolvido pela empresa [Change First](https://www.changefirst.com/), e na ExxonMobil o modelo ADKAR da empresa [Prosci](https://www.prosci.com).   
:::     



